config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root 'pins#index'
  get 'pins' => 'root'

  get 'about' => 'pages#about'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  validates :description, presence: true
  validates :user_id, presence: true
  has_attached_file :image, styles: { medium: "320x240>"}
  validates_attachment :image, 
                        presence: true,
                        size: { less_than: 5.megabytes },
                        content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] }

  def image_remote_url=(url_value)
    self.image = URI.parse(url_value) unless url_value.blank?
    super
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pins, dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    # devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :name) }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    set_pin_index
    respond_with(@pins)
  end

  def show
    set_pin_show
    respond_with(@pin)
  end

  def new
    @pin = current_user.pins.new
    respond_with(@pin)
  end

  def edit
  end

  def create
    @pin = current_user.pins.new(pin_params)
    @pin.save
    respond_with(@pin, location: :root)
  end

  def update
    @pin.update(pin_params)
    respond_with(@pin)
  end

  def destroy
    @pin.destroy
    respond_with(@pin)
  end

  private
    def set_pin_index
      if current_user
        @pins = current_user.pins.order(created_at: :desc)
      else
        @pins = Pin.order(created_at: :desc)
      end
    end

    def set_pin_show
      if current_user
        @pin = current_user.pins.find(params[:id])
      else
        @pin = Pin.find(params[:id])
      end
    end

    def set_pin
      @pin = current_user.pins.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description, :image, :image_remote_url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="footer">
        <small>
          <%= link_to '<gc/pinterest>', root_path %>
          by <%= link_to "Hethe Berg", "http://growthcode.herokuapp.com" %>
        </small>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="navbar-wrapper">
  <div class="navbar navbar-default navbar-fixed-top home-navbar" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to '<gc/pinterest>', root_path, {class: "navbar-brand home-brand"} %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav" id="main-menu">
          <li><%= link_to 'About', about_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right" id="main-menu">
          <% if user_signed_in? %>
            <li><%= link_to 'Add +', new_pin_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div><!-- Nav ends -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterest by GrowthCode</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>



</head>
<body>

  <%= render 'layouts/header' %>

  <%= yield %>

  <%= render 'layouts/footer' %>
<br>
<br>
</body>
</html>

app/views/pages/_home.html.erb
<!-- if user is not signed in -->
<% if !user_signed_in? %>
  <div class="container">
    <div class="row">
      <div class="col-md-12 well">
        <h1>Welcome to a Pinterest Clone by GrowthCode!</h1>
        <br>
        <p>
          You've found the home page for the
          <%= link_to "Pinterest Clone", root_path %>, so come on, try it out!
        </p>
        <br>
        <p>
          <%= link_to "New User", new_user_session_path, { class: "btn btn-large btn-primary" } %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/about.html.erb
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>About</h1>
        <p>
          This is a learning experience and portfolio project for <%= link_to "Hethe Berg", "growthcode.herokuapp.com" %> creating <%= link_to "Pinterest Clone", root_path %>.
        </p>
        <p>
          <i class="fa fa-cloud"></i> <a>http://growthcode-pinterest.herokuapp.com/</a>
        </p>
        <p>
          <i class="fa fa-github-square"></i> <a>http://github.com/growthcode/pinterest</a>
        </p>
      </div>
    </div>
  </div>

app/views/pages/home.html.erb
<!-- if user is not signed in -->
<% if !user_signed_in? %>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Welcome to a Pinterest Clone by GrowthCode!</h1>
        <br>
        <p>
          You've found the home page for the
          <%= link_to "Pinterest Clone", root_path %>, so come on, try it out!
        </p>
        <br>
        <p>
          <%= link_to "New User", new_user_session_path, { class: "btn btn-large btn-primary" } %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <%= f.input :image, label: "Upload an image" %>
  <%= f.input :image_remote_url, label: "or enter a URL" %>
  <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div id="boxIndexPin" class="box-index-pin">
  <%= link_to (image_tag pin.image(:medium)), pin %>
  <div class="pin-text">
    <p class="description"><%= pin.description %></p>
    <p><strong>Posted by <%= pin.user.name %></strong></p>
    <% if current_user == pin.user %>
    <p><%= link_to 'Edit', edit_pin_path(pin) %> | <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>
  </div>
</div>

app/views/pins/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Editing pin</h1>

      <%= render 'form' %>

      <%= link_to 'Show', @pin %> |
      <%= link_to 'Back', pins_path %>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<%= render 'pages/home' %>


<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div id="pins">
        <%= render @pins %>
      </div>
    </div>
  </div>
</div>

app/views/pins/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>New pin</h1>

      <%= render 'form' %>

      <%= link_to 'Back', pins_path %>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<div class="container">
  <div id="showPinRow" class="row">
    <div id="showPinContainer" class="col-xs-12">
      <div id="showPin" class="well">
        <%= image_tag @pin.image, class: "show-image" %>
        <p class="description"><%= @pin.description %></p>
        <p><%= @pin.user.name %></p>
        <% if current_user == @pin.user %>
        <%= link_to 'Edit', edit_pin_path(@pin) %> |
        <% end %>
        <%= link_to 'Back', pins_path %>
      </div>
    </div>
  </div>
</div>